### ISSUE TITLE
rstanarm diagnostic_file error

### ISSUE THREAD

**Issue by DominiqueMakowski** [quentingronau/bridgesampling#10]
Hey!

When running the following:

```r
library(rstanarm)
library(bridgesampling)

df <- psycho::standardize(attitude)
fit <- rstanarm::stan_glm(rating ~ advance, data=df)
H1 <- bridgesampling::bridge_sampler(fit , silent = TRUE)
```
It errors with the following message:

`Error in bridge_sampler.stanreg(fit, silent = TRUE) : 
  the 'diagnostic_file' option must be specified in the call to stan_glm to use the 'bridge_sampler'`

Why was this need for diagnostic_file implemented? Would it be possible to add an option to deactive this error (and maybe just print a warning or something)? Thanks!

**Comment by quentingronau** [comment]
Hi Dominique,

@bgoodri kindly added the `bridge_sampler` method for `stanreg` objects and wrote: 

>A `stanreg` object does not return enough information to call `unconstrain_pars` so the unconstrained parameters have to be read from the diagnostic files, which have to be specified in the original call. 

Therefore, I think no bridge sampling estimate can be produced if the diagnostic_file option is not specified, hence the error message. Do you have anything to add, @singmann?

Cheers,
Quentin

**Comment by singmann** [comment]
Not much to add from my side. The problem is that `rstanarm` per default does not save enough information for us to calculate the marginal likelihood without the `diagnostic_file`. So as long as `rstanarm` does not change its return element, we cannot deactivate this error. The marginal likelihood simply cannot be calculated without it.
